import type { Role } from '../roles';

export interface CheckRecord {
  id: string;
  checkNumber: string;
  checkDate: string; // display string (MM/DD/YYYY)
  checkType: string;
  companyCode: string;
  employeeCode: string;
  payType: string;
}

export interface SearchParams {
  enterpriseId: string;
  companyCode: string;
  /** Selected employee code. Empty string means "all employees". */
  employeeCode: string;
  startDate: string; // ISO YYYY-MM-DD
  endDate: string; // ISO YYYY-MM-DD
}

export interface Enterprise {
  id: string;
  name: string;
}

/** Mock enterprise directory surfaced in the searchable Enterprise ID picker. */
export const ENTERPRISES: Enterprise[] = [
  { id: 'ENT-001', name: 'Acme Corporation' },
  { id: 'ENT-002', name: 'Globex Industries' },
  { id: 'ENT-003', name: 'Initech Solutions' },
  { id: 'ENT-004', name: 'Umbrella Group' },
  { id: 'ENT-005', name: 'Stark Enterprises' },
  { id: 'ENT-006', name: 'Wayne Holdings' },
  { id: 'ENT-007', name: 'Wonka Foods' },
  { id: 'ENT-008', name: 'Cyberdyne Systems' },
];

export interface Company {
  code: string;
  name: string;
}

/** Mock company directory surfaced in the searchable Company Code picker. */
export const COMPANIES: Company[] = [
  { code: 'ACME', name: 'Acme Payroll Co.' },
  { code: 'GLOBEX', name: 'Globex Payroll' },
  { code: 'INITECH', name: 'Initech Payroll' },
  { code: 'UMBRLA', name: 'Umbrella Payroll' },
  { code: 'STARK', name: 'Stark Payroll' },
  { code: 'WAYNE', name: 'Wayne Payroll' },
];

export interface Employee {
  code: string;
  name: string;
}

/** Mock employee roster surfaced in the searchable Employee picker. */
export const EMPLOYEES: Employee[] = [
  { code: 'E1001', name: 'Jane Cooper' },
  { code: 'E1002', name: 'Wade Warren' },
  { code: 'E1003', name: 'Esther Howard' },
  { code: 'E1004', name: 'Cameron Williamson' },
  { code: 'E1005', name: 'Brooklyn Simmons' },
  { code: 'E1006', name: 'Leslie Alexander' },
  { code: 'E1007', name: 'Jenny Wilson' },
  { code: 'E1008', name: 'Guy Hawkins' },
  { code: 'E1009', name: 'Robert Fox' },
  { code: 'E1010', name: 'Kristin Watson' },
  { code: 'E1011', name: 'Cody Fisher' },
  { code: 'E1012', name: 'Savannah Nguyen' },
];

export interface AuditResult {
  /** Total checks generated by payroll for the criteria. */
  totalExpected: number;
  /** Checks confirmed loaded into ESS (the rows returned). */
  rows: CheckRecord[];
}

/** Sentinel a tester can type into Company Code to preview the empty state. */
export const EMPTY_STATE_COMPANY_CODE = 'EMPTY';

const CHECK_TYPES = ['Regular', 'Bonus', 'Final', 'Adjustment', 'Off-Cycle'];
const PAY_TYPES = [
  'Regular Wages',
  'Annual Bonus',
  'Final Pay - Termination',
  'Commission Bonus',
  'Regular Wages',
  'Severance Final',
];

/** Small deterministic string hash so identical criteria return stable results. */
function seedFrom(input: string): number {
  let h = 2166136261;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function mulberry32(seed: number): () => number {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function formatDate(iso: string): string {
  const [y, m, d] = iso.split('-');
  if (!y || !m || !d) return iso;
  return `${m}/${d}/${y}`;
}

function pickDateInRange(rand: () => number, startIso: string, endIso: string): string {
  const start = new Date(startIso).getTime();
  const end = new Date(endIso).getTime();
  const safeEnd = Number.isNaN(end) || end < start ? start : end;
  const t = start + Math.floor(rand() * (safeEnd - start + 1));
  return new Date(t).toISOString().slice(0, 10);
}

/**
 * Simulates the payroll/ESS cross-reference query. Pure and deterministic so the
 * UI never re-renders into different data for the same inputs.
 */
export function runAudit(params: SearchParams, role: Role): AuditResult {
  if (params.companyCode.trim().toUpperCase() === EMPTY_STATE_COMPANY_CODE) {
    return { totalExpected: 0, rows: [] };
  }

  const seedKey = [
    role,
    params.enterpriseId,
    params.companyCode,
    params.employeeCode,
    params.startDate,
    params.endDate,
  ].join('|');

  const rand = mulberry32(seedFrom(seedKey));
  const isSpecific = params.employeeCode.trim() !== '';

  const totalExpected = isSpecific ? 2 + Math.floor(rand() * 4) : 12 + Math.floor(rand() * 13);
  // Some generated checks never made it into ESS - that's the whole point of the audit.
  const missing = Math.floor(rand() * Math.min(4, totalExpected));
  const foundCount = Math.max(0, totalExpected - missing);

  const companyPool = params.companyCode.trim()
    ? [params.companyCode.trim().toUpperCase()]
    : ['ACME', 'GLOBEX', 'INITECH'];

  const rows: CheckRecord[] = [];
  for (let i = 0; i < foundCount; i++) {
    const typeIdx = Math.floor(rand() * CHECK_TYPES.length);
    const payIdx = Math.floor(rand() * PAY_TYPES.length);
    const employeeCode = isSpecific
      ? params.employeeCode.trim().toUpperCase()
      : EMPLOYEES[Math.floor(rand() * EMPLOYEES.length)].code;
    rows.push({
      id: `${i + 1}`,
      checkNumber: (500100 + Math.floor(rand() * 499899)).toString(),
      checkDate: formatDate(pickDateInRange(rand, params.startDate, params.endDate)),
      checkType: CHECK_TYPES[typeIdx],
      companyCode: companyPool[Math.floor(rand() * companyPool.length)],
      employeeCode,
      payType: PAY_TYPES[payIdx],
    });
  }

  return { totalExpected, rows };
}
